### ISSUE TITLE
api todo

### ISSUE THREAD

**Issue by sh4hrazad** [FeiSkyDeC/SCD#10]
- [ ] 新建并布置任务（教师） /scd/tasks/add
- [ ] 删除任务（教师） /scd/tasks/delete
- [ ] 修改任务（教师） /scd/tasks/edit
- [ ] 列出所有任务 /scd/tasks/list
- [ ] 查看某个任务 /scd/tasks/{task_id}
- [ ] 中止任务（教师） /scd/tasks/abort
- [ ] 下载任务中的附件 /scd/tasks/{task_id}/files/{file_id}
- [ ] 提交任务（学生） /scd/tasks/commits/add
- [ ] 编辑已提交的任务（学生） /scd/tasks/commits/edit
- [ ] 查看已提交的任务（学生） /scd/tasks/commits/list
- [ ] 查看单个已提交的任务 /scd/tasks/commits/{commit_id}
- [ ] 下载提交的任务中的附件 /scd/tasks/commits/{commit_id}/files/{file_id}
- [ ] 审核任务（教师） /scd/tasks/commits/verify

**Comment by FeiSkyDeC** [comment]
> * [ ] 新建并布置任务（教师） /scd/tasks/add
> * [ ] 删除任务（教师） /scd/tasks/delete
> * [ ] 修改任务（教师） /scd/tasks/edit
> * [ ] 列出所有任务 /scd/tasks/list
> * [ ] 查看某个任务 /scd/tasks/{task_id}
> * [ ] 中止任务（教师） /scd/tasks/abort
> * [ ] 下载任务中的附件 /scd/tasks/{task_id}/files/{file_id}
> * [ ] 提交任务（学生） /scd/tasks/commits/add
> * [ ] 编辑已提交的任务（学生） /scd/tasks/commits/edit
> * [ ] 查看已提交的任务（学生） /SCD/tasks/commits/list
> * [ ] 查看单个已提交的任务 /scd/tasks/commits/{commit_id}
> * [ ] 下载提交的任务中的附件 /scd/tasks/commits/{commit_id}/files/{file_id}
> * [ ] 审核任务（教师） /scd/tasks/commits/verify

行，我概括后编写在项目计划书中

**Comment by FeiSkyDeC** [comment]
问题已解决，可以在 `Documents\协作开发文档\项目文档` 中查看项目计划和任务分配
